server:
  port: 8761
spring:
  application:
    name: eurka-server
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/, http://127.0.0.1:8762/eureka/
